import type { ImageMetadata } from 'astro';
import { z } from 'zod';
import {
  captionSizes,
  colorThemeOptions,
  dividerSizes,
  employmentStatusModes,
  headingSizes,
  headingTags,
  highlightsGridVariants,
  galleryVariants,
  mediaTextDirections,
  mediaTextPairVariants,
  mediaTextVariants,
  pageHeroVariants,
  personRoles,
  spacings,
  textSectionPairVariants,
  textHeavyGridTitleStyles,
  textSectionVariants,
  threadSpans,
  type ColorThemeName,
  type ThreadSpan,
  dividerVariants,
} from '../lib/constants.ts';
import { headerImagePositions } from './blogPosts.ts';
import {
  actions,
  cmsImage,
  imageWithCaptionFor,
  number,
  linkPathMessage,
  optionalImageWithCaptionFor,
  optionalLinkPathPattern,
  action,
  markdown,
} from './shared.ts';

/**
 * SINGLE SOURCE OF TRUTH for the page builder.
 *
 * Each block is a Zod object whose `type` literal is the discriminator that both
 * Decap CMS (the "variable type" list widget) and Astro use to tell blocks apart.
 *
 * From these schemas we derive:
 *   - the Astro content collection schema (src/content.config.ts)
 *   - the Decap CMS config (public/config.yml), generated by introspecting Zod
 *     internals — see src/lib/cms/generate-config.ts
 *
 * To add a field, edit it here once. To add a new block: add it to
 * `blockSchemasFor` below, and register a matching component in
 * src/components/blocks/index.ts.
 */

/**
 * The chrome every block shares, on top of its own fields: the intro above the
 * Divider, the Divider itself, and the block's own spacing. Optional rather
 * than `.default()`, so an untouched field stays blank in the CMS and out of
 * the saved JSON — every one of these falls back to `blockDefaults` in
 * composites/Block. A component that reads one of them outside Block has to
 * apply that fallback itself.
 *
 * The intro is nested rather than flat: a flat `title` here would overwrite the
 * required `title` a block declares for itself, since defineBlock extends the
 * base last.
 */
export const blockBase = z.object({
  intro: z
    .object({
      title: z.string().optional(),
      subtitle: z.string().optional(),
      description: markdown().optional(),
      actions: actions.optional(),
      titleSize: z.enum(headingSizes).optional(),
      titleTag: z.enum(headingTags).optional(),
    })
    .optional()
    .meta({ collapsed: true }),
  dividerSize: z.enum(dividerSizes).optional(),
  dividerVariant: z.enum(dividerVariants).optional(),
  spacing: z.enum(spacings).optional(),
});

/**
 * Defines a block: its own fields, plus `blockBase`. The base is appended
 * rather than prepended so the shared controls sit below the block's own
 * fields in the CMS.
 */
const defineBlock = <T extends z.ZodRawShape>(shape: T) =>
  z.object(shape).extend(blockBase.shape);

/**
 * Blocks are defined once here, parameterised by how `image` is represented:
 * a path string for the Decap config, an Astro `image()` for the content
 * collection (see src/content.config.ts).
 */
export const blockSchemasFor = <T extends z.ZodType>(imageField: T) =>
  [
    defineBlock({
      type: z.literal('pageHero'),
      eyebrow: z.string().optional(),
      title: z.string(),
      subtitle: z.string().optional(),
      text: markdown().optional(),
      image: optionalImageWithCaptionFor(imageField),
      variant: z.enum(pageHeroVariants).optional(),
    }),
    defineBlock({
      type: z.literal('gallery'),
      images: z.array(imageWithCaptionFor(imageField)).min(1).meta({ min: 1 }),
      variant: z.enum(galleryVariants).optional(),
      gradients: z.boolean().optional(),
      captionSize: z.enum(captionSizes).optional(),
    }),
    defineBlock({
      type: z.literal('mediaText'),
      title: z.string(),
      subtitle: z.string().optional(),
      body: markdown(),
      actions: actions.optional(),
      images: z.array(imageWithCaptionFor(imageField)).min(1).meta({ min: 1 }),
      variant: z.enum(mediaTextVariants).optional(),
      direction: z.enum(mediaTextDirections).optional(),
    }),
    defineBlock({
      type: z.literal('fellowshipMediaText'),
      // A fellowship is identified by its `<year>/<slug>` directory, which lives
      // in the file path rather than the frontmatter, so there is no field for
      // the relation widget to store. `{{slug}}` is Decap's own entry slug, the
      // same path plus the "/index" file name — see fellowshipRefToId.
      fellowship: z.string().meta({
        widget: 'relation',
        collection: 'fellowships',
        // "fellows.*", not "fellows": Decap narrows a searched array down to
        // whichever elements matched, and only counts an element as matched if
        // the search field named it per-element. Plain "fellows" therefore
        // empties the array on every hit, blanking the name in the label below.
        // With the wildcard the label shows the fellow the editor searched for,
        // which is not always the first one.
        search_fields: ['title', 'fellows.*', 'year'],
        value_field: '{{slug}}',
        // Same fallback as fellowshipsCms.summary: the title is optional, so
        // always show the year and first fellow, and append the title when set.
        display_fields: [
          "{{fields.year}} — {{fields.fellows.0}}{{fields.title | ternary(': ', '')}}{{fields.title}}",
        ],
      }),
      variant: z.enum(mediaTextVariants).optional(),
      direction: z.enum(mediaTextDirections).optional(),
    }),
    defineBlock({
      type: z.literal('mediaTextPair'),
      items: z
        .array(
          z.object({
            title: z.string().optional(),
            subtitle: z.string().optional(),
            body: markdown().optional(),
            actions: actions.optional(),
            image: optionalImageWithCaptionFor(imageField),
          }),
        )
        .min(2)
        .max(2)
        .meta({
          min: 2,
          max: 2,
          collapsed: true,
          label_singular: 'Column',
          summary: '{{fields.title}}',
        }),
      variant: z.enum(mediaTextPairVariants).optional(),
      imageFirst: z.boolean().optional().meta({ label: 'Image above text' }),
    }),
    defineBlock({
      type: z.literal('grantProjectGrid'),
      // Stores the grant's `name`, which is what grantProjectSchema.grant holds
      // too, so the two compare directly.
      grant: z.string().meta({
        widget: 'relation',
        collection: 'grants',
        search_fields: ['name', 'title'],
        value_field: 'name',
        display_fields: ['name'],
      }),
    }),
    // Showcase channels are synced from Are.na, and their CMS collection is
    // hidden — see showcaseCms. The relation widget reads it all the same.
    defineBlock({
      type: z.literal('showcaseChannel'),
      channel: z.string().meta({
        widget: 'relation',
        collection: 'showcase',
        search_fields: ['name'],
        value_field: 'slug',
        display_fields: ['name'],
      }),
    }),
    defineBlock({
      type: z.literal('textSection'),
      title: z.string().optional(),
      subtitle: z.string().optional(),
      body: markdown().optional(),
      actions: actions.optional(),
      variant: z.enum(textSectionVariants).optional(),
    }),
    defineBlock({
      type: z.literal('featuredBlogPost'),
      image: imageField.optional(),
      imageAlt: z.string().optional().meta({ label: 'Alt text' }),
      // Same sharp gravity names as a blog post's own header image; the
      // component supplies the fallback — see FeaturedBlogPost.
      imagePosition: z
        .enum(headerImagePositions)
        .optional()
        .meta({ label: 'Image crop' }),
      title: z.string(),
      text: z.string().optional().meta({ widget: 'text' }),
      link: z
        .string()
        .regex(optionalLinkPathPattern, linkPathMessage)
        .optional()
        .meta({ label: 'Link (e.g. "/blog/my-post")' }),
      author: z.string().optional(),
      date: z.coerce.date().optional().meta({ widget: 'datetime' }),
      // Decap's number widget saves a string unless value_type says otherwise.
      readTime: z.coerce
        .number()
        .optional()
        .meta({ label: 'Read time (minutes)', value_type: 'int' }),
    }),
    defineBlock({
      type: z.literal('placeholderBlock'),
      title: z.string(),
      subtitle: z.string().optional(),
    }),
    defineBlock({
      type: z.literal('numbers'),
      title: z.string().optional(),
      numbers: z
        .array(number)
        .refine((arr) => new Set([3, 4, 6]).has(arr.length), {
          message: 'Provide exactly 3, 4, or 6 numbers',
        })
        .meta({
          min: 3,
          max: 6,
          hint: 'Provide exactly 3, 4, or 6 numbers.',
        }),
    }),
    defineBlock({
      type: z.literal('statementList'),
      statements: z
        .array(
          z.object({
            title: z.string(),
            description: z.string().meta({ widget: 'markdown' }),
          }),
        )
        .min(1)
        .meta({
          min: 1,
          collapsed: true,
          summary: '{{fields.title}}',
          label_singular: 'Statement',
        }),
      statementSpacing: z.enum(spacings).optional(),
    }),
    defineBlock({
      type: z.literal('horizontalStatementList'),
      statements: z
        .array(
          z.object({
            title: z.string().optional(),
            description: z.string().optional().meta({ widget: 'markdown' }),
          }),
        )
        .min(1)
        .meta({
          min: 1,
          collapsed: true,
          // Same fallback as fellowshipsCms.summary: both fields are optional
          // and Decap can't fall back from one to another, so always show the
          // start of the description and prepend the title when it is set.
          summary:
            "{{fields.title}}{{fields.title | ternary(': ', '')}}{{fields.description | truncate(60)}}",
          label_singular: 'Statement',
        }),
    }),
    defineBlock({
      type: z.literal('contactForm'),
      title: z.string(),
      body: markdown().optional(),
      formTitle: z.string().default('Submit this form'),
      topics: z.array(z.string()).default([]).meta({ label_singular: 'Topic' }),
      defaultTopic: z.string().optional(),
      submitLabel: z.string().default('Send'),
    }),
    defineBlock({
      type: z.literal('textHeavyGrid'),
      items: z
        .array(
          z.object({
            title: z.string(),
            subtitle: z.string().optional().meta({ widget: 'text' }),
            link: z
              .string()
              .regex(optionalLinkPathPattern, linkPathMessage)
              .optional()
              .meta({ label: 'Link (e.g. "/blog/my-post")' }),
            linkLabel: z
              .string()
              .optional()
              .meta({ label: 'Link label (defaults to "Read more")' }),
          }),
        )
        .default([])
        .meta({
          collapsed: true,
          summary: '{{fields.title}}',
          label_singular: 'Item',
        }),
      titleStyle: z.enum(textHeavyGridTitleStyles).default('body'),
    }),
    defineBlock({
      type: z.literal('logosText'),
      title: z.string(),
      subtitle: z.string().optional(),
      body: markdown(),
      textActions: actions.optional(),
      actionsWithImage: z
        .array(
          z.object({
            image: imageWithCaptionFor(imageField),
            action: action,
          }),
        )
        .meta({ min: 1, max: 3, hint: 'Provide 1 to 3 actions with images.' }),
      direction: z.enum(mediaTextDirections).optional(),
    }),
    // The one grid that references no collection: the editor writes each card
    // out, so it can point at a page, a blog post, or another site alike.
    defineBlock({
      type: z.literal('highlightsGrid'),
      highlights: z
        .array(
          z.object({
            image: imageField.optional(),
            imageAlt: z.string().optional().meta({ label: 'Alt text' }),
            eyebrow: z.string().optional(),
            title: z.string(),
            categories: z
              .array(z.string())
              .optional()
              .meta({ label_singular: 'Category' }),
            link: z
              .string()
              .regex(optionalLinkPathPattern, linkPathMessage)
              .optional()
              .meta({ label: 'Link (e.g. "/blog/my-post")' }),
          }),
        )
        .meta({
          collapsed: true,
          summary: '{{fields.title}}',
          label_singular: 'Highlight',
        }),
      variant: z.enum(highlightsGridVariants).default('offset'),
    }),
    defineBlock({
      type: z.literal('personHeader'),
      name: z.string(),
      title: z.string().optional(),
      eyebrow: z.string().optional(),
      image: optionalImageWithCaptionFor(imageField),
      url: z
        .string()
        .regex(optionalLinkPathPattern, linkPathMessage)
        .optional()
        .meta({ label: 'Link (e.g. "/blog/my-post")' }),
      body: markdown(),
      employmentStatus: z.enum(employmentStatusModes).optional(),
      roles: z
        .array(z.enum(personRoles))
        .optional()
        .meta({ label_singular: 'Person Roles' }),
    }),
    defineBlock({
      type: z.literal('textSectionPair'),
      title: z.string(),
      items: z
        .array(
          z.object({
            title: z.string().optional(),
            subtitle: z.string().optional(),
            body: markdown().optional(),
            actions: actions.default([]),
          }),
        )
        .default([])
        .meta({
          min: 2,
          max: 2,
          collapsed: true,
          label_singular: 'Column',
          summary: '{{fields.title}}',
        }),
      variant: z.enum(textSectionPairVariants).default('default'),
    }),
    defineBlock({
      type: z.literal('quote'),
      quote: markdown(),
      author: z.string().optional(),
    }),
  ] as const;

/** All block schemas, in the order they appear in the CMS "add block" menu. */
export const blockSchemas = blockSchemasFor(cmsImage);

/** The `blocks` list: any block, any order, repeatable. */
export const blocksUnion = z.discriminatedUnion('type', [...blockSchemas]);

/**
 * A full page definition. The route comes from the entry's own path — see
 * `meta.path` on pagesCms below — so there is no slug field.
 * `colorTheme` and `threadSpan` are the page theme: set once here, inherited
 * by every block on the page.
 */
export const pageSchema = z.object({
  title: z.string(),
  colorTheme: z
    .enum(
      Object.keys(colorThemeOptions) as [ColorThemeName, ...ColorThemeName[]],
    )
    .meta({
      widget: 'select',
      options: Object.entries(colorThemeOptions).map(([value, label]) => ({
        value,
        label,
      })),
    })
    .optional(),
  threadSpan: z
    .literal(threadSpans)
    .meta({
      widget: 'select',
      options: threadSpans.map((value) => ({ value, label: String(value) })),
    })
    .optional(),
  // Optional: a freshly-created nested/section page may have no blocks yet.
  blocks: z.array(blocksUnion).optional(),
});

/** Convenience types for components. */
export type Page = z.infer<typeof pageSchema>;

/**
 * A block as it reaches a component, once content.config.ts has swapped each
 * `image` path string for a resolved Astro asset.
 */
export type Block = z.infer<
  ReturnType<typeof blockSchemasFor<z.ZodType<ImageMetadata>>>[number]
>;
export type BlockType = Block['type'];
export type Gallery = Extract<Block, { type: 'gallery' }>;
export type PageHero = Extract<Block, { type: 'pageHero' }>;
export type Numbers = Extract<Block, { type: 'numbers' }>;
export type StatementList = Extract<Block, { type: 'statementList' }>;
export type HorizontalStatementList = Extract<
  Block,
  { type: 'horizontalStatementList' }
>;
export type MediaText = Extract<Block, { type: 'mediaText' }>;
export type FellowshipMediaText = Extract<
  Block,
  { type: 'fellowshipMediaText' }
>;
export type MediaTextPair = Extract<Block, { type: 'mediaTextPair' }>;
export type TextSection = Extract<Block, { type: 'textSection' }>;
export type FeaturedBlogPost = Extract<Block, { type: 'featuredBlogPost' }>;
export type PlaceholderBlock = Extract<Block, { type: 'placeholderBlock' }>;
export type HighlightsGrid = Extract<Block, { type: 'highlightsGrid' }>;
export type LogosText = Extract<Block, { type: 'logosText' }>;
export type ContactForm = Extract<Block, { type: 'contactForm' }>;
export type TextSectionPair = Extract<Block, { type: 'textSectionPair' }>;
export type TextHeavyGrid = Extract<Block, { type: 'textHeavyGrid' }>;
export type PersonHeader = Extract<Block, { type: 'personHeader' }>;
export type Quote = Extract<Block, { type: 'quote' }>;
export type GrantProjectGrid = Extract<Block, { type: 'grantProjectGrid' }>;
export type ShowcaseChannel = Extract<Block, { type: 'showcaseChannel' }>;

/**
 * What a block component is rendered with: its own fields plus `threadSpan`,
 * which is set once on the page and passed down rather than stored per block.
 */
export type BlockProps = Block & { threadSpan?: ThreadSpan };

/**
 * Decap CMS collection definition. `schema` drives the generated fields; the rest
 * is collection-level config Zod can't express. Consumed by src/lib/cms/generate-config.ts.
 */
export const pagesCms = {
  name: 'pages',
  label: 'Pages',
  folder: 'src/content/pages',
  create: true,
  delete: true,
  identifier_field: 'title',
  extension: 'json',
  format: 'json',
  summary: '{{title}}',
  // Lets editors nest a page inside another (making it a "section") in the CMS
  // tree. A directory node borrows the title of its index entry, so the tree
  // shows page titles rather than folder names.
  nested: { depth: 100 },
  // `index_file` switches Decap from naming a new file after the title to
  // writing whatever path the editor typed: <path>/index.json. The path is
  // therefore the URL, it is validated against the paths that already exist,
  // and editing it later moves the file.
  meta: {
    path: {
      label: 'Page path (e.g. "about/mission-and-values")',
      widget: 'string',
      index_file: 'index',
    },
  },
  schema: pageSchema,
};
