import type { ImageMetadata } from 'astro';
import { z } from 'zod';
import {
  blockDefaults,
  captionSizes,
  colorThemeOptions,
  dividerSizes,
  imagesVariants,
  mediaTextDirections,
  mediaTextPairVariants,
  mediaTextVariants,
  pageHeroVariants,
  spacings,
  textSectionVariants,
  threadSpans,
  type ColorThemeName,
  type ThreadSpan,
} from '../lib/constants.ts';
import { headerImagePositions } from './blogPosts.ts';
import {
  actions,
  cmsImage,
  imageWithCaption,
  linkPathMessage,
  optionalLinkPathPattern,
} from './shared.ts';

/**
 * SINGLE SOURCE OF TRUTH for the page builder.
 *
 * Each block is a Zod object whose `type` literal is the discriminator that both
 * Decap CMS (the "variable type" list widget) and Astro use to tell blocks apart.
 *
 * From these schemas we derive:
 *   - the Astro content collection schema (src/content.config.ts)
 *   - the Decap CMS config (public/config.yml), generated by introspecting Zod
 *     internals — see src/lib/cms/generate-config.ts
 *
 * To add a field, edit it here once. To add a new block: add it to
 * `blockSchemasFor` below, and register a matching component in
 * src/components/blocks/index.ts.
 */

/**
 * The chrome every block shares, on top of its own fields: the Divider above it
 * and its own spacing. Defaults (rather than `.optional()`) so pages saved
 * before these fields existed still validate, and so components receive a
 * concrete value instead of `undefined`.
 */
export const blockBase = z.object({
  dividerSize: z.enum(dividerSizes).default(blockDefaults.dividerSize),
  spacing: z.enum(spacings).default(blockDefaults.spacing),
});

/**
 * Defines a block: its own fields, plus `blockBase`. The base is appended
 * rather than prepended so the shared controls sit below the block's own
 * fields in the CMS.
 */
const defineBlock = <T extends z.ZodRawShape>(shape: T) =>
  z.object(shape).extend(blockBase.shape);

/**
 * Blocks are defined once here, parameterised by how `image` is represented:
 * a path string for the Decap config, an Astro `image()` for the content
 * collection (see src/content.config.ts).
 */
export const blockSchemasFor = <T extends z.ZodType>(imageField: T) =>
  [
    defineBlock({
      type: z.literal('pageHero'),
      eyebrow: z.string().optional(),
      title: z.string(),
      subtitle: z.string().optional(),
      text: z.string().optional().meta({ widget: 'markdown' }),
      // The inner field is optional too: Decap validates an object widget's
      // children even when the object itself is `required: false`, so a
      // required path here would block saving a hero with no image.
      image: imageWithCaption
        .extend({ image: imageField.optional() })
        .optional(),
      variant: z.enum(pageHeroVariants).default('default'),
    }),
    defineBlock({
      type: z.literal('images'),
      images: z.array(imageWithCaption.extend({ image: imageField })),
      variant: z.enum(imagesVariants),
      gradients: z.boolean().optional(),
      captionSize: z.enum(captionSizes).optional(),
    }),
    defineBlock({
      type: z.literal('mediaText'),
      title: z.string(),
      subtitle: z.string().optional(),
      body: z.string().meta({ widget: 'markdown' }),
      actions: actions,
      images: z.array(imageWithCaption.extend({ image: imageField })),
      variant: z.enum(mediaTextVariants).default('half'),
      direction: z.enum(mediaTextDirections).default('left-to-right'),
    }),
    defineBlock({
      type: z.literal('fellowshipMediaText'),
      // A fellowship is identified by its `<year>/<slug>` directory, which lives
      // in the file path rather than the frontmatter, so there is no field for
      // the relation widget to store. `{{slug}}` is Decap's own entry slug, the
      // same path plus the "/index" file name — see fellowshipRefToId.
      fellowship: z.string().meta({
        widget: 'relation',
        collection: 'fellowships',
        // "fellows.*", not "fellows": Decap narrows a searched array down to
        // whichever elements matched, and only counts an element as matched if
        // the search field named it per-element. Plain "fellows" therefore
        // empties the array on every hit, blanking the name in the label below.
        // With the wildcard the label shows the fellow the editor searched for,
        // which is not always the first one.
        search_fields: ['title', 'fellows.*', 'year'],
        value_field: '{{slug}}',
        // Same fallback as fellowshipsCms.summary: the title is optional, so
        // always show the year and first fellow, and append the title when set.
        display_fields: [
          "{{fields.year}} — {{fields.fellows.0}}{{fields.title | ternary(': ', '')}}{{fields.title}}",
        ],
      }),
      variant: z.enum(mediaTextVariants).default('two-thirds'),
      direction: z.enum(mediaTextDirections).default('right-to-left'),
    }),
    defineBlock({
      type: z.literal('mediaTextPair'),
      items: z
        .array(
          z.object({
            title: z.string().optional(),
            subtitle: z.string().optional(),
            body: z.string().optional().meta({ widget: 'markdown' }),
            actions: actions.default([]),
            // The inner field is optional too: Decap validates an object
            // widget's children even when the object itself is
            // `required: false` — same reason as pageHero's image.
            image: imageWithCaption
              .extend({ image: imageField.optional() })
              .optional(),
          }),
        )
        .default([])
        .meta({
          min: 2,
          max: 2,
          collapsed: true,
          label_singular: 'Column',
          summary: '{{fields.title}}',
        }),
      variant: z.enum(mediaTextPairVariants).default('default'),
      imageFirst: z.boolean().default(false).meta({
        label: 'Image above text',
        required: false,
      }),
    }),
    defineBlock({
      type: z.literal('textSection'),
      title: z.string(),
      subtitle: z.string().optional(),
      body: z.string().optional().meta({ widget: 'markdown' }),
      actions: actions.default([]),
      variant: z.enum(textSectionVariants).default('default'),
    }),
    defineBlock({
      type: z.literal('featuredBlogPost'),
      image: imageField.optional(),
      imageAlt: z.string().optional().meta({ label: 'Alt text' }),
      // Same sharp gravity names as a blog post's own header image, and the same
      // `required: false` reason — see headerImagePosition in blogPosts.ts.
      imagePosition: z
        .enum(headerImagePositions)
        .default('center')
        .meta({ label: 'Image crop', required: false }),
      title: z.string(),
      text: z.string().optional().meta({ widget: 'text' }),
      link: z
        .string()
        .regex(optionalLinkPathPattern, linkPathMessage)
        .optional()
        .meta({ label: 'Link (e.g. "/blog/my-post")' }),
      author: z.string().optional(),
      date: z.coerce.date().optional().meta({ widget: 'datetime' }),
      // Decap's number widget saves a string unless value_type says otherwise.
      readTime: z.coerce
        .number()
        .optional()
        .meta({ label: 'Read time (minutes)', value_type: 'int' }),
    }),
    defineBlock({
      type: z.literal('placeholderBlock'),
      label: z.string(),
    }),
    defineBlock({
      type: z.literal('statementList'),
      statements: z
        .array(
          z.object({
            title: z.string(),
            description: z.string(),
          }),
        )
        .meta({
          collapsed: true,
          summary: '{{fields.title}}',
          label_singular: 'Statement',
        }),
      statementSpacing: z.enum(spacings).optional(),
    }),
    defineBlock({
      type: z.literal('horizontalStatementList'),
      statements: z
        .array(
          z.object({
            title: z.string(),
            description: z.string(),
          }),
        )
        .meta({
          collapsed: true,
          summary: '{{fields.title}}',
          label_singular: 'Statement',
        }),
    }),
  ] as const;

/** All block schemas, in the order they appear in the CMS "add block" menu. */
export const blockSchemas = blockSchemasFor(cmsImage);

/** The `blocks` list: any block, any order, repeatable. */
export const blocksUnion = z.discriminatedUnion('type', [...blockSchemas]);

/**
 * A full page definition. `slug` defines the route's leaf segment.
 * `colorTheme` and `threadSpan` are the page theme: set once here, inherited
 * by every block on the page.
 */
export const pageSchema = z.object({
  title: z.string(),
  slug: z.string().regex(/^[^/]+$/, "Slug can't contain a slash"),
  colorTheme: z
    .enum(
      Object.keys(colorThemeOptions) as [ColorThemeName, ...ColorThemeName[]],
    )
    .meta({
      widget: 'select',
      options: Object.entries(colorThemeOptions).map(([value, label]) => ({
        value,
        label,
      })),
    })
    .default('default'),
  threadSpan: z
    .literal(threadSpans)
    .meta({
      widget: 'select',
      options: threadSpans.map((value) => ({ value, label: String(value) })),
    })
    .default(blockDefaults.threadSpan),
  // Optional: a freshly-created nested/section page may have no blocks yet.
  blocks: z.array(blocksUnion).optional(),
});

/** Convenience types for components. */
export type Page = z.infer<typeof pageSchema>;

/**
 * A block as it reaches a component, once content.config.ts has swapped each
 * `image` path string for a resolved Astro asset.
 */
export type Block = z.infer<
  ReturnType<typeof blockSchemasFor<z.ZodType<ImageMetadata>>>[number]
>;
export type BlockType = Block['type'];
export type Images = Extract<Block, { type: 'images' }>;
export type PageHero = Extract<Block, { type: 'pageHero' }>;
export type StatementList = Extract<Block, { type: 'statementList' }>;
export type HorizontalStatementList = Extract<
  Block,
  { type: 'horizontalStatementList' }
>;
export type MediaText = Extract<Block, { type: 'mediaText' }>;
export type FellowshipMediaText = Extract<
  Block,
  { type: 'fellowshipMediaText' }
>;
export type MediaTextPair = Extract<Block, { type: 'mediaTextPair' }>;
export type TextSection = Extract<Block, { type: 'textSection' }>;
export type FeaturedBlogPost = Extract<Block, { type: 'featuredBlogPost' }>;
export type PlaceholderBlock = Extract<Block, { type: 'placeholderBlock' }>;

/**
 * What a block component is rendered with: its own fields plus `threadSpan`,
 * which is set once on the page and passed down rather than stored per block.
 */
export type BlockProps = Block & { threadSpan?: ThreadSpan };

/**
 * Decap CMS collection definition. `schema` drives the generated fields; the rest
 * is collection-level config Zod can't express. Consumed by src/lib/cms/generate-config.ts.
 */
export const pagesCms = {
  name: 'pages',
  label: 'Pages',
  folder: 'src/content/pages',
  create: true,
  delete: true,
  identifier_field: 'title',
  extension: 'json',
  format: 'json',
  summary: '{{title}}',
  // Lets editors nest a page inside another (making it a "section") in the CMS tree.
  // subfolders: false keeps a folder's own name visible in the tree instead of
  // borrowing its single child page's title.
  nested: { depth: 100, subfolders: false },
  // KNOWN GAP: two pages saved under the same parent with the same (or
  // similarly-slugified) title silently overwrite each other's file — Decap
  // names new nested entries from the title with no collision check. Fixing
  // this for real needs `meta.path.index_file` plus a custom widget that
  // combines "parent to nest under" + "this page's own name" into one path
  // (so Decap's own pathExists validation has something real to check).
  // Decap's own path validator hard-rejects an empty value (no `required: false`
  // can override that), so a top-level page needs a value that still resolves to
  // the collection root: "/" round-trips through its per-segment slug check
  // unchanged, and collapses away when joined into the final file path.
  meta: {
    path: {
      label: 'Parent page ("/" for a top-level page)',
      widget: 'page-path',
      default: '/',
    },
  },
  schema: pageSchema,
};
